### ISSUE TITLE
Upload source code on github

### ISSUE THREAD

**Issue by psdsantos** [yasirrhaq/EPIC-RPG-Autotyper#1]

**Comment by yasirrhaq** [comment]
Hi there, sorry  i wasn't really active atm on my github. I dont think i can upload the source code since it will encourage other people to make bot? xD

**Comment by yasirrhaq** [comment]
Hi there, sorry for the late reply. I don't really think I will upload the source (idk where the source code is, since I've changed my laptop) and i don't think i will continue this project anymore
