### ISSUE TITLE
Some problem with command 4, 5 and 6

### ISSUE THREAD

**Issue by phatyuio** [yasirrhaq/EPIC-RPG-Autotyper#4]
I notice that the program will not work if you put the command 2, 3 combines with command 4th, it will just occasionally do 4th, and then shut it out(I have tried it with notepad to check the frequency). I know you have stopped developing this program, and I am really appreciated your effort, but can you please finish it, to not waste the most function auto typer I have tried. This is the picture about frequency and the picture of how I set up it. If you read this, thanks for your time!!
![image](https://user-images.githubusercontent.com/75473914/108410334-dff58f00-7259-11eb-9fd5-33cc54b760d7.png)
![image](https://user-images.githubusercontent.com/75473914/108410464-0c111000-725a-11eb-8b40-84a6a71cf42b.png)

**Comment by yasirrhaq** [comment]
Hi there, sorry for the late reply. I think that is because the epoch timer doesn't really sync with any server times so this bug happened. If I have spare time ill make a new version for this autotyper and make it open source. Thank you

**Comment by StefanoCastro** [comment]
Command 4, 5 and 6 only work once for me and then never again until I stop and start again. Then it works again just once
