### ISSUE TITLE
Add rpg hunt t in command 1

### ISSUE THREAD

**Issue by StefanoCastro** [yasirrhaq/EPIC-RPG-Autotyper#5]
Since commands 4, 5 and 6 don't really work (well) can you add "rpg hunt t" into the dropdownlist of command 1, next to rpg hunt?

**Comment by StefanoCastro** [comment]
Update: Command 4, 5 and 6 only work once for me and then never again until I stop and start again. Then it works again just once

**Comment by yasirrhaq** [comment]
Yes, ill add it later if I have spare time to do this project. Currently, I'm still doing another project at this moment. Might create a new one and release it for public and make it open source

**Comment by StefanoCastro** [comment]
Any news on this? It's been a while
